### ISSUE TITLE
Generation sample for POP909

### ISSUE THREAD

**Issue by zero-nnkn** [Natooz/BPE-Symbolic-Music#1]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/60695920/229475499-34449a3a-65ae-4f52-a179-1d91b2c512cc.png">

Can you provide some generation samples (prompt +  continuations) from your trained model (used for Human evaluations)?

**Comment by Natooz** [comment]
Hey,
Sure, just send me an email or tweeter dm so I can privately send you the sharing link
I also have to say that we are currently retraining all models with new training procedures and model size, which should result in much better results for all experiments. We will update the paper consequently.

**Comment by zero-nnkn** [comment]
Yeah, thank you, my email is nnkhoinguyen9@gmail.com
I'm looking forward to your updates about the new training procedures and model 🤩
